pipeline {
    agent any
    tools {
        terraform 'tf20207'
    }
    stages {
        stage('Hello') {
            steps {
                echo 'Hello World2'
            }
        }
        stage('Terraform Deployment') {
            steps {
                withCredentials([file(credentialsId: 'gcp-terraform', variable: 'tf_auth_key')]) {
                    sh 'terraform -chdir=hybridcloudpoc init'
                    sh 'terraform -chdir=hybridcloudpoc plan -var "tf_auth_key=${tf_auth_key}"'
                    sh 'terraform -chdir=hybridcloudpoc apply -var "tf_auth_key=${tf_auth_key}" --auto-approve'
                }
            }
        }
    }
}
